=== ht5678/TestProject/build/classes/xml/schema/02.xsd
<?xml version="1.0" encoding="UTF-8"?>
<schema xmlns="http://www.w3.org/2001/XMLSchema" 
				targetNamespace="http://www.example.org/02" 
				xmlns:tns="http://www.example.org/02" 
				elementFormDefault="qualified">

	<element name="books">
		<complexType><!-- unbounded表示不限制 -->
			<sequence minOccurs="0" maxOccurs="unbounded">
				<element name="book" >
					<complexType>
						<sequence>
							<element name="id" type="int"></element>
							<element name="title" type="string"></element>
							<element name="content" type="string"></element>
							<choice>
								<element name="author" type="string"></element>
								<element name="authors">
									<complexType>
										<sequence minOccurs="1" maxOccurs="3">
											<element name="author"></element>
										</sequence>
									</complexType>
								</element>
							</choice>
						</sequence>
						<!-- 属性attribute要在sequence之后 -->
						<attribute name="isbn" type="string" use="required"></attribute>
						<!--  <attribute name="isbn" type="string" use="optional"></attribute>-->
					</complexType>
				</element>
			</sequence>
		</complexType>
	</element>
	
</schema>

=== ht5678/TestProject/build/classes/xml/schema/02_test.xml
<?xml version="1.0" encoding="UTF-8"?>
<books xmlns="http://www.example.org/02"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://www.example.org/02 02.xsd">

	<!-- 第一种情况  choice选择第一种 -->
	<book isbn="12345">
		<id>1101</id>
		<title>java基础</title>
		<content>java的入门级教程，让你有信心</content>
		<author>zhangsan</author>
	</book>
	
	<!-- 第一种情况  choice选择第二种 -->
	<book isbn="23456">
		<id>1102</id>
		<title>java web入门</title>
		<content>java web 的入门级教程</content>
		<authors>
			<author>zhangsan</author>
			<author>lisi</author>
			<author>wangwu</author>
		</authors>
	</book>
</books>
